sudo: required
language: go
go:
- 1.9
go_import_path: github.com/whatedcgveg/v2ray-core
git:
  depth: 5
before_script:
- sudo ntpdate -u time.google.com
- date
script:
- go test -p 1 -tags json -v github.com/whatedcgveg/v2ray-core/...
after_success:
- ./testing/coverage/coverall
